spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: http://localhost:3306/firstgame?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    password: root
    username: root
server:
  port: 8085