spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firstgame?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    password: root
    username: root
server:
  port: 5555
#mybatis-plus配置以及代码生成器is_deleted字段策略配置
mybatis-plus:
  type-aliases-package: cn.ch.firstgamestart.entity
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      logic-delete-field: isDeleted